# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', models.CharField(blank=True, max_length=200, null=True)),
                ('bed_size', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.CharField(blank=True, max_length=200, null=True)),
                ('occupants', models.CharField(blank=True, max_length=200, null=True)),
                ('days_to_stay', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'RoomReservations',
            },
        ),
    ]
